### ISSUE TITLE
how to make this work with Redis has auth?

### ISSUE THREAD

**Issue by Doltair** [bitcrowd/rails-monitoring#18]
```
 "#<Redis::CommandError: NOAUTH Authentication required.>",
```

**Comment by juffel** [comment]
Hi Doltair!

This engine uses the redis connection from the parent app (via `Sidekiq.redis`) so you should be able to configure Redis AUTH within the Sidekiq configuration of your parent app.  
It might be as simple as [this StackOverflow answer](https://stackoverflow.com/a/25979761/1870317) suggests:
```
config.redis = { password: 'bar' }
```
